import type { Metadata } from "next";
import "./globals.css";
import { firaCode } from "./fonts";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Lokendra Nath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${firaCode.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
